[package]
name = "gameshare"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.11"
futures-util = "0.3"
log = "0.4.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tokio-tungstenite = "0.30.0"
uuid = { version = "1", features = ["v4", "fast-rng"] }
webrtc = "0.20"
