signaling_addr = "wss://gameshare-clientview.fly.dev/signaling"
target_framerate = 30
target_bitrate = 5000
resolution = { width = 1920, height = 1080 }
use_nvenc = true

[video]
target_framerate = 30
target_bitrate = 5000  # kbps
width = 1920
height = 1080
use_nvenc = true

[capture]
window_title = ""  # Optional: specific window title to capture
process_name = ""  # Optional: specific process name to capture  
capture_cursor = true
capture_audio = true

[encoding]
codec = "h264"
preset = "ultrafast"  # For x264: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
crf = 23  # For x264: 0-51, lower is better quality
keyframe_interval = 30  # frames
low_latency = true

[input]
enable_mouse = true
enable_keyboard = true
mouse_sensitivity = 1.0
input_lag_compensation = true

# WebRTC Configuration
[[webrtc.ice_servers]]
urls = ["stun:stun.l.google.com:19302"]

[[webrtc.ice_servers]]
urls = ["stun:stun1.l.google.com:19302"]

# Add TURN servers if needed for NAT traversal
[[webrtc.ice_servers]]
urls = ["turn:global.relay.metered.ca:80", "turn:global.relay.metered.ca:443?transport=tcp"]
username = "f5e9b6f5df726ad6e7f4e8e9"
credential = "Gk4EhT4xJCdXgY8p"

[webrtc]
data_channel_ordered = false
video_codec = "H264"
audio_codec = "opus" 