# fly.toml app configuration file generated for gameshare-web-tabeeb on 2025-08-03T00:22:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gameshare-web-tabeeb'
primary_region = 'ord'

# Using Dockerfile instead of buildpacks

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
